version: 0.0.0.{build}
branches:
  only:
  - master
  - csharp7migration
skip_tags: true
image: Visual Studio 2017
build:
  verbosity: minimal
before_build:
  - nuget restore
configuration:
  - Appveyor
